# Generated by Django 4.2 on 2026-01-31 20:18

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("terms_accepted", models.BooleanField(default=False)),
                ("terms_accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CompanyFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("season", "Season"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "collected_from",
                    models.CharField(
                        default="weekly_pool",
                        help_text="weekly_pool or season_pot",
                        max_length=50,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collected", "Collected"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Company Fee",
                "verbose_name_plural": "Company Fees",
                "db_table": "company_fees",
            },
        ),
        migrations.CreateModel(
            name="MLBPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mlb_player_id", models.IntegerField(unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("team_name", models.CharField(max_length=50)),
                ("team_abbreviation", models.CharField(max_length=10)),
                ("position", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_pitcher", models.BooleanField(default=False)),
                (
                    "is_two_way_player",
                    models.BooleanField(
                        default=False, help_text="Players like Ohtani who pitch and bat"
                    ),
                ),
                ("mlb_team_id", models.IntegerField(blank=True, null=True)),
                ("jersey_number", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "MLB Player",
                "verbose_name_plural": "MLB Players",
                "db_table": "mlb_players",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Pick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_auto_copied", models.BooleanField(default=False)),
                (
                    "points_earned",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("hit", "Hit"),
                            ("miss", "Miss"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scored_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pick",
                "verbose_name_plural": "Picks",
                "db_table": "picks",
            },
        ),
        migrations.CreateModel(
            name="PickCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "requires_pitcher",
                    models.BooleanField(
                        default=False,
                        help_text="True for SWP and S, False for 2H and HR",
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pick Category",
                "verbose_name_plural": "Pick Categories",
                "db_table": "pick_categories",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="SeasonPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.IntegerField()),
                (
                    "placement",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                ("total_points", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="50, 35, or 15", max_digits=5
                    ),
                ),
                (
                    "payout_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("venmo", "Venmo"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paypal_payout_batch_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payout_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Season Payout",
                "verbose_name_plural": "Season Payouts",
                "db_table": "season_payouts",
            },
        ),
        migrations.CreateModel(
            name="SeasonPot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.IntegerField()),
                (
                    "total_accumulated",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "first_place_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "second_place_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "third_place_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("is_finalized", models.BooleanField(default=False)),
                ("is_distributed", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Season Pot",
                "verbose_name_plural": "Season Pots",
                "db_table": "season_pots",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "weekly_fee",
                    models.DecimalField(
                        choices=[
                            (Decimal("5.00"), "$5 per week"),
                            (Decimal("10.00"), "$10 per week"),
                        ],
                        decimal_places=2,
                        help_text="Weekly entry fee per player",
                        max_digits=5,
                    ),
                ),
                (
                    "season_year",
                    models.IntegerField(
                        help_text="Which MLB season this team plays in"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Show team on public leaderboards"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_members",
                    models.IntegerField(
                        default=3,
                        help_text="Minimum 3 members required",
                        validators=[django.core.validators.MinValueValidator(3)],
                    ),
                ),
                (
                    "max_members",
                    models.IntegerField(
                        blank=True, help_text="Optional member limit", null=True
                    ),
                ),
                (
                    "join_code",
                    models.CharField(
                        blank=True,
                        help_text="Secret code for players to join",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "stripe_connected_account_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paypal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "auto_payout_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automated payouts via Stripe/PayPal",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "teams",
                "ordering": ["-season_year", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invited_user_email", models.EmailField(max_length=254)),
                (
                    "invitation_type",
                    models.CharField(
                        choices=[
                            ("invite", "Captain Invite"),
                            ("request", "Join Request"),
                        ],
                        default="invite",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=64, unique=True)),
                ("message", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Invitation",
                "verbose_name_plural": "Team Invitations",
                "db_table": "team_invitations",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("captain", "Captain"),
                            ("co_captain", "Co-Captain"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "db_table": "team_members",
            },
        ),
        migrations.CreateModel(
            name="TeamStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.IntegerField()),
                ("total_members", models.IntegerField(default=0)),
                ("active_members", models.IntegerField(default=0)),
                ("total_team_points", models.IntegerField(default=0)),
                (
                    "average_points_per_member",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("total_perfect_weeks", models.IntegerField(default=0)),
                (
                    "participation_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="% of members who play each week",
                        max_digits=5,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Standing",
                "verbose_name_plural": "Team Standings",
                "db_table": "team_standings",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Chicago",
                        help_text="User timezone for deadline calculations",
                        max_length=50,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "venmo_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paypal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_payout_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("venmo", "Venmo"),
                            ("manual", "Manual/Cash"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "total_lifetime_winnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_lifetime_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.IntegerField()),
                ("total_points", models.IntegerField(default=0)),
                ("total_picks_made", models.IntegerField(default=0)),
                ("total_picks_hit", models.IntegerField(default=0)),
                (
                    "accuracy_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("weeks_participated", models.IntegerField(default=0)),
                ("perfect_weeks", models.IntegerField(default=0)),
                ("highest_weekly_score", models.IntegerField(default=0)),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, help_text="Consecutive weeks with at least 1 hit"
                    ),
                ),
                ("longest_streak", models.IntegerField(default=0)),
                ("team_rank", models.IntegerField(blank=True, null=True)),
                (
                    "total_winnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Standing",
                "verbose_name_plural": "User Standings",
                "db_table": "user_standings",
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(26),
                        ]
                    ),
                ),
                ("season_year", models.IntegerField()),
                (
                    "saturday_date",
                    models.DateField(help_text="The specific Saturday for this week"),
                ),
                (
                    "deadline_utc",
                    models.DateTimeField(
                        help_text="Deadline in UTC (11 AM CST = 5 PM UTC)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one week should be active at a time",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("games_start_time", models.DateTimeField(blank=True, null=True)),
                ("games_end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Week",
                "verbose_name_plural": "Weeks",
                "db_table": "weeks",
                "ordering": ["season_year", "week_number"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achieved",
                    models.BooleanField(
                        default=False, help_text="Did player achieve this stat?"
                    ),
                ),
                (
                    "stat_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual stat value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("game_date", models.DateField()),
                ("game_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "opponent_team",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.pickcategory",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.mlbplayer",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.week",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Result",
                "verbose_name_plural": "Weekly Results",
                "db_table": "weekly_results",
            },
        ),
        migrations.CreateModel(
            name="WeeklyPrizePool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "rollover_from_previous",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount rolled over from previous week",
                        max_digits=10,
                    ),
                ),
                (
                    "weekly_pool_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="80% of collections + rollover",
                        max_digits=10,
                    ),
                ),
                (
                    "season_pot_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="10% of new collections",
                        max_digits=10,
                    ),
                ),
                (
                    "company_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="10% of new collections",
                        max_digits=10,
                    ),
                ),
                (
                    "per_pick_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=5
                    ),
                ),
                ("num_perfect_picks", models.IntegerField(default=0)),
                (
                    "payout_per_winner",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "rollover_to_next",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount rolling to next week if no winners",
                        max_digits=10,
                    ),
                ),
                ("is_distributed", models.BooleanField(default=False)),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_scored",
                    models.BooleanField(
                        default=False, help_text="Has this week been scored?"
                    ),
                ),
                (
                    "scored_at",
                    models.DateTimeField(
                        blank=True, help_text="When picks were scored", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distributed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributed_pools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_prize_pools",
                        to="core.team",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prize_pools",
                        to="core.week",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Prize Pool",
                "verbose_name_plural": "Weekly Prize Pools",
                "db_table": "weekly_prize_pools",
            },
        ),
        migrations.CreateModel(
            name="WeeklyPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("perfect_picks", models.IntegerField(default=4)),
                ("total_picks", models.IntegerField(default=4)),
                (
                    "payout_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("manual", "Manual"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("venmo", "Venmo"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paypal_payout_batch_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payout_date", models.DateTimeField(blank=True, null=True)),
                ("payout_initiated_at", models.DateTimeField(blank=True, null=True)),
                ("last_payout_error", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_payouts",
                        to="core.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="core.week",
                    ),
                ),
                (
                    "weekly_prize_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="core.weeklyprizepool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Payout",
                "verbose_name_plural": "Weekly Payouts",
                "db_table": "weekly_payouts",
            },
        ),
        migrations.CreateModel(
            name="WeeklyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("venmo", "Venmo"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paypal_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("last_payment_error", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_payments",
                        to="core.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.week",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Payment",
                "verbose_name_plural": "Weekly Payments",
                "db_table": "weekly_payments",
            },
        ),
        migrations.AddIndex(
            model_name="week",
            index=models.Index(
                fields=["season_year", "week_number"], name="weeks_season__478322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="week",
            index=models.Index(fields=["is_active"], name="weeks_is_acti_864b4c_idx"),
        ),
        migrations.AddIndex(
            model_name="week",
            index=models.Index(
                fields=["saturday_date"], name="weeks_saturda_fa8dae_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("week_number", "season_year")},
        ),
        migrations.AddField(
            model_name="userstanding",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_standings",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="userstanding",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teamstanding",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standings",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="invited_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                help_text="Team admin/creator",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="captained_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seasonpot",
            name="distributed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="distributed_season_pots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seasonpot",
            name="first_place_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first_place_seasons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seasonpot",
            name="second_place_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_place_seasons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seasonpot",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_pots",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="seasonpot",
            name="third_place_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="third_place_seasons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seasonpayout",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_season_payouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seasonpayout",
            name="season_pot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="core.seasonpot",
            ),
        ),
        migrations.AddField(
            model_name="seasonpayout",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_payouts",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="seasonpayout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_payouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picks",
                to="core.pickcategory",
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="copied_from_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copied_picks",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picks",
                to="core.mlbplayer",
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picks",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picks",
                to="core.week",
            ),
        ),
        migrations.AddIndex(
            model_name="mlbplayer",
            index=models.Index(
                fields=["mlb_player_id"], name="mlb_players_mlb_pla_92d77b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlbplayer",
            index=models.Index(
                fields=["team_abbreviation"], name="mlb_players_team_ab_56cece_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlbplayer",
            index=models.Index(
                fields=["is_active"], name="mlb_players_is_acti_649901_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlbplayer",
            index=models.Index(
                fields=["is_pitcher", "is_active"],
                name="mlb_players_is_pitc_7ae3b3_idx",
            ),
        ),
        migrations.AddField(
            model_name="companyfee",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_fees",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="companyfee",
            name="week",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_fees",
                to="core.week",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyresult",
            index=models.Index(
                fields=["week", "achieved"], name="weekly_resu_week_id_bf6a63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyresult",
            index=models.Index(
                fields=["player", "week"], name="weekly_resu_player__133f2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyresult",
            index=models.Index(
                fields=["category", "week", "achieved"],
                name="weekly_resu_categor_568240_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weeklyresult",
            unique_together={("week", "player", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="weeklyprizepool",
            unique_together={("team", "week")},
        ),
        migrations.AddIndex(
            model_name="weeklypayout",
            index=models.Index(
                fields=["user", "week"], name="weekly_payo_user_id_4db55f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklypayout",
            index=models.Index(
                fields=["team", "week"], name="weekly_payo_team_id_ddc4b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklypayout",
            index=models.Index(
                fields=["payout_status"], name="weekly_payo_payout__dd444b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklypayment",
            index=models.Index(
                fields=["team", "week", "payment_status"],
                name="weekly_paym_team_id_8b1ae2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklypayment",
            index=models.Index(
                fields=["user", "payment_status"], name="weekly_paym_user_id_f19543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklypayment",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="weekly_paym_stripe__e14fcd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklypayment",
            index=models.Index(
                fields=["paypal_transaction_id"], name="weekly_paym_paypal__89e04a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weeklypayment",
            unique_together={("user", "team", "week")},
        ),
        migrations.AddIndex(
            model_name="userstanding",
            index=models.Index(
                fields=["team", "season_year", "total_points"],
                name="user_standi_team_id_049cc8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userstanding",
            index=models.Index(
                fields=["season_year", "total_points"],
                name="user_standi_season__2387fe_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userstanding",
            unique_together={("user", "team", "season_year")},
        ),
        migrations.AddIndex(
            model_name="teamstanding",
            index=models.Index(
                fields=["season_year", "total_team_points"],
                name="team_standi_season__2273ce_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamstanding",
            unique_together={("team", "season_year")},
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["team", "status"], name="team_member_team_id_62e01f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(fields=["user"], name="team_member_user_id_906d63_idx"),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["user", "status"], name="team_member_user_id_f73d2b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "user", "status")},
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(fields=["token"], name="team_invita_token_5620a6_idx"),
        ),
        migrations.AddIndex(
            model_name="teaminvitation",
            index=models.Index(
                fields=["team", "status"], name="team_invita_team_id_d0b794_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teaminvitation",
            unique_together={("team", "invited_user_email", "status")},
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["captain"], name="teams_captain_fc5fc9_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["season_year"], name="teams_season__1ec438_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["season_year", "is_public"], name="teams_season__4c58ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["join_code"], name="teams_join_co_cb7c84_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="seasonpot",
            unique_together={("team", "season_year")},
        ),
        migrations.AddIndex(
            model_name="pick",
            index=models.Index(
                fields=["user", "week"], name="picks_user_id_524d5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pick",
            index=models.Index(
                fields=["week", "result_status"], name="picks_week_id_910ff2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pick",
            index=models.Index(
                fields=["player", "week"], name="picks_player__269df2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pick",
            index=models.Index(fields=["user"], name="picks_user_id_c67a54_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="pick",
            unique_together={("user", "team", "week", "category")},
        ),
    ]
