# Generated by Django 4.2 on 2026-02-06 02:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="account_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Current account balance available for payments",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_low_balance_alert",
            field=models.DateTimeField(
                blank=True,
                help_text="When was the last low balance alert sent?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="low_balance_alert_sent",
            field=models.BooleanField(
                default=False,
                help_text="Has low balance alert been sent for current balance?",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="low_balance_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15.00"),
                help_text="Alert user when balance drops below this amount",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture (max 5MB)",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_payout_method",
            field=models.CharField(
                choices=[
                    ("balance", "Keep in Account Balance"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("venmo", "Venmo"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_lifetime_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount paid in weekly fees over all time",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_lifetime_winnings",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount won over all time (before payouts)",
                max_digits=10,
            ),
        ),

        migrations.CreateModel(
            name="AccountTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("adjustment", "Admin Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Human-readable description", max_length=200
                    ),
                ),
                (
                    "stripe_transfer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "paypal_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "venmo_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "total_lifetime_winnings",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_lifetime_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who processed this transaction (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.weeklypayment",
                    ),
                ),
                (
                    "related_payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="core.weeklypayout",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
            },
        ),
    ]
