# Generated by Django 4.2 on 2026-02-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounttransaction",
            name="total_lifetime_paid",
        ),
        migrations.RemoveField(
            model_name="accounttransaction",
            name="total_lifetime_winnings",
        ),
    ]
