# Generated by Django 4.2 on 2026-02-06 19:53

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Account Transaction",
                "verbose_name_plural": "Account Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="accounttransaction",
            name="total_lifetime_paid",
        ),
        migrations.RemoveField(
            model_name="accounttransaction",
            name="total_lifetime_winnings",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 6, 19, 53, 20, 32439, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_payout_method",
            field=models.CharField(
                choices=[
                    ("balance", "Keep in Account Balance"),
                    ("stripe", "Bank Transfer (Stripe)"),
                    ("paypal", "PayPal"),
                    ("venmo", "Venmo"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_lifetime_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount paid in weekly fees",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="total_lifetime_winnings",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount won over all time",
                max_digits=10,
            ),
        ),
        migrations.AddIndex(
            model_name="accounttransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="account_tra_user_id_9b66e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accounttransaction",
            index=models.Index(
                fields=["transaction_type", "status"],
                name="account_tra_transac_fb122d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accounttransaction",
            index=models.Index(
                fields=["related_payment"], name="account_tra_related_a19576_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accounttransaction",
            index=models.Index(
                fields=["related_payout"], name="account_tra_related_d760a4_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="accounttransaction",
            table="account_transactions",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table=None,
        ),
    ]
