# Generated by Django 4.2 on 2026-02-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_season_prepay_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="preferred_payout_method",
            field=models.CharField(
                choices=[
                    ("balance", "Keep in Account Balance"),
                    ("stripe", "Bank Transfer (Stripe)"),
                    ("paypal", "PayPal"),
                    ("venmo", "Venmo"),
                ],
                default="balance",
                max_length=20,
            ),
        ),
    ]
