"""
Django settings for Pick4baseball project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
logging.warning(">>> LOADED Pick4baseball/settings.py <<<")

import logging
logging.warning("SETTINGS FILE LOADED: settings.py")


from pathlib import Path
import os

AUTH_USER_MODEL = 'core.User'

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&!f1rl0jr_1^w^n%9cptgz)7vhoxv03aluuat-2$t7%)lw)%po"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['cheald10.pythonanywhere.com', 'localhost', '127.0.0.1']

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    'core',
    'widget_tweaks',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Pick4baseball.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Pick4baseball.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "cheald10$default",
        "USER": "cheald10",
        "PASSWORD": "Pick4db2025!",
        "HOST": "cheald10.mysql.pythonanywhere-services.com",
        "PORT": "3306",
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        "TEST": {
            "NAME": "cheald10$test_baseballpick4",
            "CREATE_DB": False,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Where Django will collect static files for production (PythonAnywhere)
STATIC_ROOT = '/home/cheald10/PythonAW/Pick4baseball/static_collected/'

# Where your app-level static files live during development
#STATICFILES_DIRS = [
#    BASE_DIR / 'core/static',
#]

# Media files (uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

# Force production email for testing
USE_PRODUCTION_EMAIL = True

if DEBUG and not USE_PRODUCTION_EMAIL:
    # Development: Emails print to console
    EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
    DEFAULT_FROM_EMAIL = 'Baseball Pick 4 <claytonheald@gmail.com>'
    print("📧 Email Backend: Console")
else:
    # Production: SendGrid SMTP
    EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'apikey'  # This is literal - don't change it
    SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
    SENDGRID_SANDBOX_MODE_IN_DEBUG = False
    DEFAULT_FROM_EMAIL = 'Heald & Heritage <support@healdandheritage.com>'
    SERVER_EMAIL = 'support@healdandheritage.com'
    print("📧 Email Backend: SendGrid")

    import sys
    print("PYTHON RUNTIME:", sys.executable)
# Email verification timeout
EMAIL_VERIFICATION_TIMEOUT_HOURS = 24

# ==============================================================================
# DJANGO SITES FRAMEWORK
# ==============================================================================

SITE_ID = 1

# ==============================================================================
# TOKEN EXPIRATION
# ==============================================================================

PASSWORD_RESET_TIMEOUT = 86400  # 24 hours
# ==============================================================================
# AUTHENTICATION SETTINGS
# ==============================================================================

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# ==============================================================================
# STRIPE PAYMENT CONFIGURATION
# ==============================================================================

STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# Validate Stripe keys are present (optional - helpful for debugging)
if not STRIPE_PUBLISHABLE_KEY:
    print("⚠️  WARNING: STRIPE_PUBLISHABLE_KEY not set in .env file")
if not STRIPE_SECRET_KEY:
    print("⚠️  WARNING: STRIPE_SECRET_KEY not set in .env file")
if not STRIPE_WEBHOOK_SECRET:
    print("⚠️  WARNING: STRIPE_WEBHOOK_SECRET not set in .env file")

# Payment Settings
COMPANY_FEE_PERCENTAGE = 0.10  # 10% fee per week
SEASON_POT_PERCENTAGE = 0.25   # 25% to end-of-season pot from rollovers
PAYMENT_DEADLINE_HOURS_BEFORE = 24  # Payment due 24 hours before picks deadline
AUTO_PAYOUT_THRESHOLD = 100.00  # Minimum amount for automatic payout
PAYOUT_DELAY_DAYS = 1  # Days to wait before processing payouts